name: CD Pipeline

on:
  workflow_call:

jobs:

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Backend Deploy
        run: |
          if [ "${{ github.event.workflow_run.head_branch }}" = "master" ]; then
            curl -X POST ${{ secrets.RENDER_BACKEND_PRODUCTION_HOOK }}
          else
            curl -X POST ${{ secrets.RENDER_BACKEND_STAGING_HOOK }}
          fi

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Frontend Deploy
        run: |
          if [ "${{ github.event.workflow_run.head_branch }}" = "master" ]; then
            curl -X POST ${{ secrets.RENDER_FRONTEND_PRODUCTION_HOOK }}
          else
            curl -X POST ${{ secrets.RENDER_FRONTEND_STAGING_HOOK }}
          fi